In [1]:
import sys
from pathlib import Path

# Add the src directory to Python path
sys.path.insert(0, str(Path().resolve().parent / 'src'))

from config import EXTERNAL_DATA_DIR, INTERIM_DATA_DIR
import pandas as pd
import requests
from datetime import datetime, timedelta
import time

2026-02-21 18:13:20.238 | INFO     | config:<module>:5 - PROJ_ROOT path is: /Users/vince/Developer/indian_pizza_machine/backend

In [2]:
# Generate all possible weekly date ranges from May 31, 2024 to now
from datetime import datetime, timedelta

# Start date: May 31, 2024 (the earliest known market is may-31 to june-7)
start_date = datetime(2024, 5, 31)
# End date: Today
end_date = datetime.now()

# Generate weekly date ranges (assuming markets run Friday-Friday, 7 days)
weekly_ranges = []
current_date = start_date

while current_date < end_date:
    week_end = current_date + timedelta(days=7)
    weekly_ranges.append({
        'start': current_date,
        'end': week_end
    })
    current_date = week_end

print(f"Generated {len(weekly_ranges)} weekly date ranges")
print(f"From: {weekly_ranges[0]['start'].strftime('%Y-%m-%d')} to {weekly_ranges[0]['end'].strftime('%Y-%m-%d')}")
print(f"To: {weekly_ranges[-1]['start'].strftime('%Y-%m-%d')} to {weekly_ranges[-1]['end'].strftime('%Y-%m-%d')}")

Generated 91 weekly date ranges
From: 2024-05-31 to 2024-06-07
To: 2026-02-20 to 2026-02-27

In [3]:
# Function to generate possible slug patterns for a date range
def generate_slug_patterns(start_date, end_date):
    """Generate possible slug patterns for a given date range."""
    patterns = []
    
    # Both full and abbreviated month names
    start_month_full = start_date.strftime('%B').lower()
    start_month_abbr = start_date.strftime('%b').lower()
    # Polymarket uses "sept" instead of "sep"
    if start_month_abbr == 'sep':
        start_month_abbr = 'sept'
    start_day = start_date.day
    
    # Try end date and end_date ± 1 day (Polymarket sometimes uses different conventions)
    for day_offset in [0, -1, 1]:
        adjusted_end = end_date + timedelta(days=day_offset)
        end_month_full = adjusted_end.strftime('%B').lower()
        end_month_abbr = adjusted_end.strftime('%b').lower()
        # Polymarket uses "sept" instead of "sep"
        if end_month_abbr == 'sep':
            end_month_abbr = 'sept'
        end_day = adjusted_end.day
        
        # Try all combinations of full/abbreviated month names
        for start_m, end_m in [(start_month_full, end_month_full), 
                                (start_month_abbr, end_month_abbr)]:
            # Pattern 1: "elon-musk-of-tweets-{month}-{day}-{month}-{day}"
            patterns.append(f"elon-musk-of-tweets-{start_m}-{start_day}-{end_m}-{end_day}")
            
            # Pattern 2: "of-elon-musk-tweets-between-{month}-{day}-and-{month}-{day}"
            patterns.append(f"of-elon-musk-tweets-between-{start_m}-{start_day}-and-{end_m}-{end_day}")
            
            # Pattern 3: "of-elon-musk-tweets-{month}-{day}-{month}-{day}" (without "between")
            patterns.append(f"of-elon-musk-tweets-{start_m}-{start_day}-{end_m}-{end_day}")
            
            # Pattern 4: Short form when same month (e.g., "oct-11-18" or "october-11-18")
            if start_m == end_m:
                patterns.append(f"elon-musk-of-tweets-{start_m}-{start_day}-{end_day}")
                # Pattern 5: "of-elon-musk-tweets-{month}-{day}-{day}" (short form with "of" prefix)
                patterns.append(f"of-elon-musk-tweets-{start_m}-{start_day}-{end_day}")
    
    # Remove duplicates while preserving order
    seen = set()
    unique_patterns = []
    for p in patterns:
        if p not in seen:
            seen.add(p)
            unique_patterns.append(p)
    
    return unique_patterns

# Function to fetch condition IDs (blobs) from Polymarket API
def get_polymarket_condition_id(slug):
    """
    Fetch the condition ID for a given market slug from Polymarket.
    
    Args:
        slug: The market slug
    
    Returns:
        dict: Market data including condition_id and other metadata, or None if not found
    """
    try:
        url = f"https://gamma-api.polymarket.com/events?slug={slug}"
        response = requests.get(url, timeout=10)
        
        if response.status_code == 200:
            data = response.json()
            if data and len(data) > 0:
                event = data[0]
                return {
                    'slug': slug,
                    'condition_id': event.get('conditionId'),
                    'title': event.get('title'),
                    'description': event.get('description'),
                    'end_date': event.get('endDate'),
                    'markets': event.get('markets', [])
                }
        return None
    except Exception as e:
        return None

print("Functions defined successfully")

Functions defined successfully

In [4]:
# Fetch all market blobs by trying different slug patterns
musk_blobs = []
attempted_slugs = []
found_slugs = []
missed_weeks = []  # Track which weeks were not found

print(f"Searching for markets across {len(weekly_ranges)} weekly periods...\n")

for i, date_range in enumerate(weekly_ranges):
    start = date_range['start']
    end = date_range['end']
    
    # Generate possible slug patterns for this date range
    patterns = generate_slug_patterns(start, end)
    
    # Try each pattern
    found = False
    for pattern in patterns:
        attempted_slugs.append(pattern)
        market_data = get_polymarket_condition_id(pattern)
        
        if market_data:
            musk_blobs.append(market_data)
            found_slugs.append(pattern)
            print(f"✓ [{len(musk_blobs)}] {start.strftime('%Y-%m-%d')} to {end.strftime('%Y-%m-%d')}")
            print(f"   {pattern}")
            found = True
            break  # Found it, move to next week
        
        # Small delay between attempts
        time.sleep(0.3)
    
    if not found:
        missed_weeks.append({
            'start': start,
            'end': end,
            'week_num': i + 1
        })
        if i % 10 == 0:
            print(f"  [{i+1}/{len(weekly_ranges)}] Checked {start.strftime('%Y-%m-%d')}... (not found)")

print(f"\n{'='*70}")
print(f"Results:")
print(f"  Attempted: {len(attempted_slugs)} slug patterns")
print(f"  Found: {len(musk_blobs)} markets")
print(f"  Missed: {len(missed_weeks)} weeks")
print(f"  Success rate: {len(musk_blobs)/len(weekly_ranges)*100:.1f}%")
print(f"{'='*70}")

Searching for markets across 91 weekly periods...

✓ [1] 2024-05-31 to 2024-06-07
   of-elon-musk-tweets-between-may-31-and-june-7
✓ [2] 2024-06-07 to 2024-06-14
   of-elon-musk-tweets-june-7-14
✓ [3] 2024-06-14 to 2024-06-21
   elon-musk-of-tweets-june-14-21
✓ [4] 2024-06-21 to 2024-06-28
   elon-musk-of-tweets-june-21-28
✓ [5] 2024-06-28 to 2024-07-05
   elon-musk-of-tweets-june-28-july-5
✓ [6] 2024-07-05 to 2024-07-12
   elon-musk-of-tweets-july-5-july-12
✓ [7] 2024-07-12 to 2024-07-19
   elon-musk-of-tweets-july-12-july-19
✓ [8] 2024-07-19 to 2024-07-26
   elon-musk-of-tweets-july-19-26
✓ [9] 2024-08-02 to 2024-08-09
   elon-musk-of-tweets-august-2-9
✓ [10] 2024-08-09 to 2024-08-16
   elon-musk-of-tweets-august-9-16
✓ [11] 2024-08-16 to 2024-08-23
   elon-musk-of-tweets-august-16-23
✓ [12] 2024-08-23 to 2024-08-30
   elon-musk-of-tweets-august-23-30
✓ [13] 2024-09-06 to 2024-09-13
   elon-musk-of-tweets-sept-6-13
✓ [14] 2024-09-13 to 2024-09-20
   elon-musk-of-tweets-sept-13-20
✓ [15] 2024-09-20 to 2024-09-27
   elon-musk-of-tweets-sept-20-27
✓ [16] 2024-09-27 to 2024-10-04
   elon-musk-of-tweets-sept-27-oct-4
✓ [17] 2024-10-04 to 2024-10-11
   elon-musk-of-tweets-oct-4-11
✓ [18] 2024-10-11 to 2024-10-18
   elon-musk-of-tweets-oct-11-18
✓ [19] 2024-10-18 to 2024-10-25
   elon-musk-of-tweets-oct-18-25
✓ [20] 2024-10-25 to 2024-11-01
   elon-musk-of-tweets-oct-25-nov-1
✓ [21] 2024-11-01 to 2024-11-08
   elon-musk-of-tweets-nov-1-8
✓ [22] 2024-11-08 to 2024-11-15
   elon-musk-of-tweets-nov-8-15
✓ [23] 2024-11-15 to 2024-11-22
   elon-musk-of-tweets-nov-15-22
✓ [24] 2024-11-22 to 2024-11-29
   elon-musk-of-tweets-nov-22-29
✓ [25] 2024-11-29 to 2024-12-06
   elon-musk-of-tweets-nov-29-dec-6
✓ [26] 2024-12-06 to 2024-12-13
   elon-musk-of-tweets-december-6-13
✓ [27] 2024-12-13 to 2024-12-20
   elon-musk-of-tweets-december-13-20
✓ [28] 2024-12-20 to 2024-12-27
   elon-musk-of-tweets-december-20-27
✓ [29] 2024-12-27 to 2025-01-03
   elon-musk-of-tweets-december-27-january-3
✓ [30] 2025-01-03 to 2025-01-10
   elon-musk-of-tweets-january-3-january-10
✓ [31] 2025-01-10 to 2025-01-17
   elon-musk-of-tweets-january-10-17
✓ [32] 2025-01-17 to 2025-01-24
   elon-musk-of-tweets-january-17-24
✓ [33] 2025-01-24 to 2025-01-31
   elon-musk-of-tweets-january-24-31
✓ [34] 2025-01-31 to 2025-02-07
   elon-musk-of-tweets-jan-31-feb-7
✓ [35] 2025-02-07 to 2025-02-14
   elon-musk-of-tweets-feb-7-14
✓ [36] 2025-02-14 to 2025-02-21
   elon-musk-of-tweets-feb-14-21
✓ [37] 2025-02-21 to 2025-02-28
   elon-musk-of-tweets-feb-21-28
✓ [38] 2025-02-28 to 2025-03-07
   elon-musk-of-tweets-feb-28-mar-7
✓ [39] 2025-03-07 to 2025-03-14
   elon-musk-of-tweets-mar-7-14
✓ [40] 2025-03-14 to 2025-03-21
   elon-musk-of-tweets-mar-14-21
✓ [41] 2025-03-21 to 2025-03-28
   elon-musk-of-tweets-mar-21-28
✓ [42] 2025-03-28 to 2025-04-04
   elon-musk-of-tweets-mar-28-apr-4
✓ [43] 2025-04-04 to 2025-04-11
   elon-musk-of-tweets-april-4-11
✓ [44] 2025-04-18 to 2025-04-25
   elon-musk-of-tweets-april-18-25
✓ [45] 2025-04-25 to 2025-05-02
   elon-musk-of-tweets-april-25-may-2
✓ [46] 2025-05-02 to 2025-05-09
   elon-musk-of-tweets-may-2-9
✓ [47] 2025-05-09 to 2025-05-16
   elon-musk-of-tweets-may-9-16
✓ [48] 2025-05-16 to 2025-05-23
   elon-musk-of-tweets-may-16-23
✓ [49] 2025-05-23 to 2025-05-30
   elon-musk-of-tweets-may-23-30
✓ [50] 2025-05-30 to 2025-06-06
   elon-musk-of-tweets-may-30-june-6
✓ [51] 2025-06-06 to 2025-06-13
   elon-musk-of-tweets-june-6-13
✓ [52] 2025-06-13 to 2025-06-20
   elon-musk-of-tweets-june-13-20
✓ [53] 2025-06-20 to 2025-06-27
   elon-musk-of-tweets-june-20-27
✓ [54] 2025-06-27 to 2025-07-04
   elon-musk-of-tweets-june-27-july-4
✓ [55] 2025-07-04 to 2025-07-11
   elon-musk-of-tweets-july-4-11
✓ [56] 2025-07-11 to 2025-07-18
   elon-musk-of-tweets-july-11-18
✓ [57] 2025-07-18 to 2025-07-25
   elon-musk-of-tweets-july-18-25
✓ [58] 2025-07-25 to 2025-08-01
   elon-musk-of-tweets-july-25-august-1
✓ [59] 2025-08-01 to 2025-08-08
   elon-musk-of-tweets-august-1-8
✓ [60] 2025-08-08 to 2025-08-15
   elon-musk-of-tweets-august-8-15
✓ [61] 2025-08-15 to 2025-08-22
   elon-musk-of-tweets-august-15-22
✓ [62] 2025-08-22 to 2025-08-29
   elon-musk-of-tweets-august-22-29
✓ [63] 2025-08-29 to 2025-09-05
   elon-musk-of-tweets-august-29-september-5
✓ [64] 2025-09-05 to 2025-09-12
   elon-musk-of-tweets-september-5-12
✓ [65] 2025-09-12 to 2025-09-19
   elon-musk-of-tweets-september-12-september-19
✓ [66] 2025-09-19 to 2025-09-26
   elon-musk-of-tweets-september-19-september-26
✓ [67] 2025-09-26 to 2025-10-03
   elon-musk-of-tweets-september-26-october-3
✓ [68] 2025-10-03 to 2025-10-10
   elon-musk-of-tweets-october-3-october-10
✓ [69] 2025-10-10 to 2025-10-17
   elon-musk-of-tweets-october-10-october-17
✓ [70] 2025-10-17 to 2025-10-24
   elon-musk-of-tweets-october-17-october-24
✓ [71] 2025-10-24 to 2025-10-31
   elon-musk-of-tweets-october-24-october-31
✓ [72] 2025-10-31 to 2025-11-07
   elon-musk-of-tweets-october-31-november-7
✓ [73] 2025-11-07 to 2025-11-14
   elon-musk-of-tweets-november-7-november-14
✓ [74] 2025-11-14 to 2025-11-21
   elon-musk-of-tweets-november-14-november-21
✓ [75] 2025-11-21 to 2025-11-28
   elon-musk-of-tweets-november-21-november-28
✓ [76] 2025-11-28 to 2025-12-05
   elon-musk-of-tweets-november-28-december-5
✓ [77] 2025-12-05 to 2025-12-12
   elon-musk-of-tweets-december-5-december-12
✓ [78] 2025-12-12 to 2025-12-19
   elon-musk-of-tweets-december-12-december-19
✓ [79] 2025-12-19 to 2025-12-26
   elon-musk-of-tweets-december-19-december-26
✓ [80] 2025-12-26 to 2026-01-02
   elon-musk-of-tweets-december-26-january-2
✓ [81] 2026-01-02 to 2026-01-09
   elon-musk-of-tweets-january-2-january-9
✓ [82] 2026-01-09 to 2026-01-16
   elon-musk-of-tweets-january-9-january-16
✓ [83] 2026-01-16 to 2026-01-23
   elon-musk-of-tweets-january-16-january-23
✓ [84] 2026-01-23 to 2026-01-30
   elon-musk-of-tweets-january-23-january-30
✓ [85] 2026-01-30 to 2026-02-06
   elon-musk-of-tweets-january-30-february-6
✓ [86] 2026-02-06 to 2026-02-13
   elon-musk-of-tweets-february-6-february-13
✓ [87] 2026-02-13 to 2026-02-20
   elon-musk-of-tweets-february-13-february-20
✓ [88] 2026-02-20 to 2026-02-27
   elon-musk-of-tweets-february-20-february-27

======================================================================
Results:
  Attempted: 395 slug patterns
  Found: 88 markets
  Missed: 3 weeks
  Success rate: 96.7%
======================================================================

In [5]:
# Display missed weeks
print(f"Missed {len(missed_weeks)} weeks:\n")

for missed in missed_weeks:
    start = missed['start']
    end = missed['end']
    week_num = missed['week_num']
    
    print(f"Week #{week_num}: {start.strftime('%Y-%m-%d')} to {end.strftime('%Y-%m-%d')}")
    print(f"  ({start.strftime('%B %d')} to {end.strftime('%B %d, %Y')})")
    
    # Show what patterns were tried for this week
    patterns = generate_slug_patterns(start, end)
    print(f"  Tried {len(patterns)} patterns:")
    for i, p in enumerate(patterns[:3], 1):  # Show first 3
        print(f"    {i}. {p}")
    if len(patterns) > 3:
        print(f"    ... and {len(patterns) - 3} more")
    print()

# Create a DataFrame of missed weeks
if len(missed_weeks) > 0:
    missed_df = pd.DataFrame([
        {
            'week_num': m['week_num'],
            'start_date': m['start'].strftime('%Y-%m-%d'),
            'end_date': m['end'].strftime('%Y-%m-%d'),
            'date_range': f"{m['start'].strftime('%b %d')} - {m['end'].strftime('%b %d, %Y')}"
        }
        for m in missed_weeks
    ])
    print("\nMissed Weeks DataFrame:")
    display(missed_df)

Missed 3 weeks:

Week #9: 2024-07-26 to 2024-08-02
  (July 26 to August 02, 2024)
  Tried 18 patterns:
    1. elon-musk-of-tweets-july-26-august-2
    2. of-elon-musk-tweets-between-july-26-and-august-2
    3. of-elon-musk-tweets-july-26-august-2
    ... and 15 more

Week #14: 2024-08-30 to 2024-09-06
  (August 30 to September 06, 2024)
  Tried 18 patterns:
    1. elon-musk-of-tweets-august-30-september-6
    2. of-elon-musk-tweets-between-august-30-and-september-6
    3. of-elon-musk-tweets-august-30-september-6
    ... and 15 more

Week #46: 2025-04-11 to 2025-04-18
  (April 11 to April 18, 2025)
  Tried 30 patterns:
    1. elon-musk-of-tweets-april-11-april-18
    2. of-elon-musk-tweets-between-april-11-and-april-18
    3. of-elon-musk-tweets-april-11-april-18
    ... and 27 more


Missed Weeks DataFrame:

   week_num  start_date    end_date             date_range
0         9  2024-07-26  2024-08-02  Jul 26 - Aug 02, 2024
1        14  2024-08-30  2024-09-06  Aug 30 - Sep 06, 2024
2        46  2025-04-11  2025-04-18  Apr 11 - Apr 18, 2025

In [6]:
# Display the collected market blobs
print("Musk Tweet Markets:\n")

for i, blob in enumerate(musk_blobs, 1):
    print(f"{i}. {blob['title']}")
    print(f"   Slug: {blob['slug']}")
    print(f"   Condition ID: {blob['condition_id']}")
    print(f"   End Date: {blob['end_date']}")
    print(f"   Markets: {len(blob.get('markets', []))}")
    print()

# Create a DataFrame for easy analysis
musk_markets_df = pd.DataFrame([
    {
        'slug': blob['slug'],
        'condition_id': blob['condition_id'],
        'title': blob['title'],
        'end_date': blob['end_date'],
        'num_markets': len(blob.get('markets', []))
    }
    for blob in musk_blobs
])

print("\nMarkets DataFrame:")
musk_markets_df

Musk Tweet Markets:

1. Elon Musk # of tweets May 31 - June 7?
   Slug: of-elon-musk-tweets-between-may-31-and-june-7
   Condition ID: None
   End Date: 2024-06-07T12:00:00Z
   Markets: 8

2. Elon Musk # of tweets June 7-14?
   Slug: of-elon-musk-tweets-june-7-14
   Condition ID: None
   End Date: 2024-06-14T12:00:00Z
   Markets: 8

3. Elon Musk # of tweets June 14-21?
   Slug: elon-musk-of-tweets-june-14-21
   Condition ID: None
   End Date: 2024-06-21T12:00:00Z
   Markets: 8

4. Elon Musk # of tweets June 21-28?
   Slug: elon-musk-of-tweets-june-21-28
   Condition ID: None
   End Date: 2024-06-28T12:00:00Z
   Markets: 8

5. Elon Musk # of tweets June 28 - July 5?
   Slug: elon-musk-of-tweets-june-28-july-5
   Condition ID: None
   End Date: 2024-07-05T12:00:00Z
   Markets: 8

6. Elon Musk # of tweets July 5 - July 12?
   Slug: elon-musk-of-tweets-july-5-july-12
   Condition ID: None
   End Date: 2024-07-12T12:00:00Z
   Markets: 8

7. Elon Musk # of tweets July 12 - July 19?
   Slug: elon-musk-of-tweets-july-12-july-19
   Condition ID: None
   End Date: 2024-07-19T12:00:00Z
   Markets: 8

8. Elon Musk # of tweets July 19-26?
   Slug: elon-musk-of-tweets-july-19-26
   Condition ID: None
   End Date: 2024-07-26T12:00:00Z
   Markets: 8

9. Elon Musk # of tweets August 2-9?
   Slug: elon-musk-of-tweets-august-2-9
   Condition ID: None
   End Date: 2024-08-09T12:00:00Z
   Markets: 9

10. Elon Musk # of tweets August 9-16?
   Slug: elon-musk-of-tweets-august-9-16
   Condition ID: None
   End Date: 2024-08-16T12:00:00Z
   Markets: 9

11. Elon Musk # of tweets August 16-23?
   Slug: elon-musk-of-tweets-august-16-23
   Condition ID: None
   End Date: 2024-08-23T12:00:00Z
   Markets: 10

12. Elon Musk # of tweets August 23-30?
   Slug: elon-musk-of-tweets-august-23-30
   Condition ID: None
   End Date: 2024-08-30T12:00:00Z
   Markets: 11

13. Elon Musk # of tweets Sept 6-13?
   Slug: elon-musk-of-tweets-sept-6-13
   Condition ID: None
   End Date: 2024-09-13T12:00:00Z
   Markets: 10

14. Elon Musk # of tweets Sept 13-20?
   Slug: elon-musk-of-tweets-sept-13-20
   Condition ID: None
   End Date: 2024-09-20T12:00:00Z
   Markets: 10

15. Elon Musk # of tweets Sept 20-27?
   Slug: elon-musk-of-tweets-sept-20-27
   Condition ID: None
   End Date: 2024-09-27T12:00:00Z
   Markets: 10

16. Elon Musk # of tweets Sept 27- Oct 4?
   Slug: elon-musk-of-tweets-sept-27-oct-4
   Condition ID: None
   End Date: 2024-10-04T12:00:00Z
   Markets: 10

17. Elon Musk # of tweets Oct 4-11?
   Slug: elon-musk-of-tweets-oct-4-11
   Condition ID: None
   End Date: 2024-10-11T12:00:00Z
   Markets: 12

18. Elon Musk # of tweets Oct 11-18?
   Slug: elon-musk-of-tweets-oct-11-18
   Condition ID: None
   End Date: 2024-10-18T12:00:00Z
   Markets: 10

19. Elon Musk # of tweets Oct 18-25?
   Slug: elon-musk-of-tweets-oct-18-25
   Condition ID: None
   End Date: 2024-10-25T12:00:00Z
   Markets: 10

20. Elon Musk # of tweets Oct 25 - Nov 1?
   Slug: elon-musk-of-tweets-oct-25-nov-1
   Condition ID: None
   End Date: 2024-11-01T12:00:00Z
   Markets: 12

21. Elon Musk # of tweets Nov 1-8?
   Slug: elon-musk-of-tweets-nov-1-8
   Condition ID: None
   End Date: 2024-11-08T12:00:00Z
   Markets: 16

22. Elon Musk # of tweets Nov 8-15?
   Slug: elon-musk-of-tweets-nov-8-15
   Condition ID: None
   End Date: None
   Markets: 14

23. Elon Musk # of tweets Nov 15-22?
   Slug: elon-musk-of-tweets-nov-15-22
   Condition ID: None
   End Date: 2024-11-22T12:00:00Z
   Markets: 12

24. Elon Musk # of tweets Nov 22-29?
   Slug: elon-musk-of-tweets-nov-22-29
   Condition ID: None
   End Date: 2024-11-29T12:00:00Z
   Markets: 12

25. Elon Musk # of tweets Nov 29-Dec 6?
   Slug: elon-musk-of-tweets-nov-29-dec-6
   Condition ID: None
   End Date: 2024-12-06T12:00:00Z
   Markets: 12

26. Elon Musk # of tweets December 6-13?
   Slug: elon-musk-of-tweets-december-6-13
   Condition ID: None
   End Date: 2024-12-13T12:00:00Z
   Markets: 10

27. Elon Musk # of tweets December 13-20?
   Slug: elon-musk-of-tweets-december-13-20
   Condition ID: None
   End Date: 2024-12-20T12:00:00Z
   Markets: 10

28. Elon Musk # of tweets December 20-27?
   Slug: elon-musk-of-tweets-december-20-27
   Condition ID: None
   End Date: 2024-12-27T12:00:00Z
   Markets: 12

29. Elon Musk # of tweets December 27-January 3?
   Slug: elon-musk-of-tweets-december-27-january-3
   Condition ID: None
   End Date: 2025-01-03T12:00:00Z
   Markets: 10

30. Elon Musk # of tweets January 3-10?
   Slug: elon-musk-of-tweets-january-3-january-10
   Condition ID: None
   End Date: 2025-01-10T17:00:00Z
   Markets: 12

31. Elon Musk # of tweets January 10-17?
   Slug: elon-musk-of-tweets-january-10-17
   Condition ID: None
   End Date: 2025-01-17T12:00:00Z
   Markets: 10

32. Elon Musk # of tweets January 17-24?
   Slug: elon-musk-of-tweets-january-17-24
   Condition ID: None
   End Date: 2025-01-24T12:00:00Z
   Markets: 12

33. Elon Musk # of tweets January 24-31?
   Slug: elon-musk-of-tweets-january-24-31
   Condition ID: None
   End Date: 2025-01-31T12:00:00Z
   Markets: 14

34. Elon Musk # of tweets Jan 31 - Feb 7?
   Slug: elon-musk-of-tweets-jan-31-feb-7
   Condition ID: None
   End Date: 2025-02-07T12:00:00Z
   Markets: 12

35. Elon Musk # of tweets Feb 7-14?
   Slug: elon-musk-of-tweets-feb-7-14
   Condition ID: None
   End Date: 2025-02-14T12:00:00Z
   Markets: 12

36. Elon Musk # of tweets Feb 14-21?
   Slug: elon-musk-of-tweets-feb-14-21
   Condition ID: None
   End Date: 2025-02-21T12:00:00Z
   Markets: 12

37. Elon Musk # of tweets Feb 21-28?
   Slug: elon-musk-of-tweets-feb-21-28
   Condition ID: None
   End Date: 2025-02-28T12:00:00Z
   Markets: 12

38. Elon Musk # of tweets Feb 28 - Mar 7?
   Slug: elon-musk-of-tweets-feb-28-mar-7
   Condition ID: None
   End Date: 2025-03-07T12:00:00Z
   Markets: 12

39. Elon Musk # of tweets Mar 7-14?
   Slug: elon-musk-of-tweets-mar-7-14
   Condition ID: None
   End Date: 2025-03-14T12:00:00Z
   Markets: 16

40. Elon Musk # of tweets Mar 14-21?
   Slug: elon-musk-of-tweets-mar-14-21
   Condition ID: None
   End Date: 2025-03-21T12:00:00Z
   Markets: 14

41. Elon Musk # of tweets Mar 21-28?
   Slug: elon-musk-of-tweets-mar-21-28
   Condition ID: None
   End Date: 2025-03-28T12:00:00Z
   Markets: 16

42. Elon Musk # of tweets Mar 28- Apr 4?
   Slug: elon-musk-of-tweets-mar-28-apr-4
   Condition ID: None
   End Date: 2025-04-04T12:00:00Z
   Markets: 16

43. Elon Musk # of tweets April 4-11?
   Slug: elon-musk-of-tweets-april-4-11
   Condition ID: None
   End Date: 2025-04-11T12:00:00Z
   Markets: 16

44. Elon Musk # of tweets April 18-25?
   Slug: elon-musk-of-tweets-april-18-25
   Condition ID: None
   End Date: 2025-04-25T12:00:00Z
   Markets: 14

45. Elon Musk # of tweets April 25- May 2?
   Slug: elon-musk-of-tweets-april-25-may-2
   Condition ID: None
   End Date: 2025-05-02T12:00:00Z
   Markets: 14

46. Elon Musk # of tweets May 2-9?
   Slug: elon-musk-of-tweets-may-2-9
   Condition ID: None
   End Date: 2025-05-09T12:00:00Z
   Markets: 12

47. Elon Musk # of tweets May 9-16?
   Slug: elon-musk-of-tweets-may-9-16
   Condition ID: None
   End Date: 2025-05-16T12:00:00Z
   Markets: 12

48. Elon Musk # of tweets May 16-23?
   Slug: elon-musk-of-tweets-may-16-23
   Condition ID: None
   End Date: 2025-05-23T12:00:00Z
   Markets: 12

49. Elon Musk # of tweets May 23-30?
   Slug: elon-musk-of-tweets-may-23-30
   Condition ID: None
   End Date: 2025-05-30T12:00:00Z
   Markets: 12

50. Elon Musk # of tweets May 30 - June 6?
   Slug: elon-musk-of-tweets-may-30-june-6
   Condition ID: None
   End Date: 2025-06-06T12:00:00Z
   Markets: 12

51. Elon Musk # of tweets June 6-13?
   Slug: elon-musk-of-tweets-june-6-13
   Condition ID: None
   End Date: 2025-06-13T00:00:00Z
   Markets: 16

52. Elon Musk # of tweets June 13-20?
   Slug: elon-musk-of-tweets-june-13-20
   Condition ID: None
   End Date: 2025-06-20T00:00:00Z
   Markets: 15

53. Elon Musk # of tweets June 20-27?
   Slug: elon-musk-of-tweets-june-20-27
   Condition ID: None
   End Date: 2025-06-27T16:00:00Z
   Markets: 15

54. Elon Musk # of tweets June 27 - July 4?
   Slug: elon-musk-of-tweets-june-27-july-4
   Condition ID: None
   End Date: 2025-07-04T00:00:00Z
   Markets: 14

55. Elon Musk # of tweets July 4-11?
   Slug: elon-musk-of-tweets-july-4-11
   Condition ID: None
   End Date: 2025-07-11T16:00:00Z
   Markets: 14

56. Elon Musk # of tweets July 11-18?
   Slug: elon-musk-of-tweets-july-11-18
   Condition ID: None
   End Date: 2025-07-18T00:00:00Z
   Markets: 13

57. Elon Musk # of tweets July 18-25?
   Slug: elon-musk-of-tweets-july-18-25
   Condition ID: None
   End Date: 2025-07-25T00:00:00Z
   Markets: 13

58. Elon Musk # of tweets July 25 - August 1?
   Slug: elon-musk-of-tweets-july-25-august-1
   Condition ID: None
   End Date: 2025-08-01T16:00:00Z
   Markets: 13

59. Elon Musk # of tweets August 1-8?
   Slug: elon-musk-of-tweets-august-1-8
   Condition ID: None
   End Date: 2025-08-08T16:00:00Z
   Markets: 13

60. Elon Musk # of tweets August 8-15?
   Slug: elon-musk-of-tweets-august-8-15
   Condition ID: None
   End Date: 2025-08-15T04:00:00Z
   Markets: 19

61. Elon Musk # of tweets August 15-22?
   Slug: elon-musk-of-tweets-august-15-22
   Condition ID: None
   End Date: 2025-08-22T16:00:00Z
   Markets: 18

62. Elon Musk # of tweets August 22-29?
   Slug: elon-musk-of-tweets-august-22-29
   Condition ID: None
   End Date: 2025-08-29T16:00:00Z
   Markets: 22

63. Elon Musk # of tweets August 29 - September 5?
   Slug: elon-musk-of-tweets-august-29-september-5
   Condition ID: None
   End Date: 2025-09-05T04:00:00Z
   Markets: 22

64. Elon Musk # of tweets September 5-12?
   Slug: elon-musk-of-tweets-september-5-12
   Condition ID: None
   End Date: 2025-09-12T16:00:00Z
   Markets: 22

65. Elon Musk # tweets September 12 - September 19, 2025?
   Slug: elon-musk-of-tweets-september-12-september-19
   Condition ID: None
   End Date: 2025-09-19T16:00:00Z
   Markets: 30

66. Elon Musk musk # tweets September 19 - September 26, 2025?
   Slug: elon-musk-of-tweets-september-19-september-26
   Condition ID: None
   End Date: 2025-09-26T16:00:00Z
   Markets: 30

67. Elon Musk # tweets September 26 - October 3, 2025?
   Slug: elon-musk-of-tweets-september-26-october-3
   Condition ID: None
   End Date: 2025-10-03T16:00:00Z
   Markets: 26

68. Elon Musk # tweets October 3 - October 10, 2025?
   Slug: elon-musk-of-tweets-october-3-october-10
   Condition ID: None
   End Date: 2025-10-10T16:00:00Z
   Markets: 26

69. Elon Musk # tweets October 10 - October 17, 2025?
   Slug: elon-musk-of-tweets-october-10-october-17
   Condition ID: None
   End Date: 2025-10-17T16:00:00Z
   Markets: 26

70. Elon Musk # tweets October 17 - October 24, 2025?
   Slug: elon-musk-of-tweets-october-17-october-24
   Condition ID: None
   End Date: 2025-10-24T16:00:00Z
   Markets: 26

71. Elon Musk # tweets October 24 - October 31, 2025?
   Slug: elon-musk-of-tweets-october-24-october-31
   Condition ID: None
   End Date: 2025-10-31T16:00:00Z
   Markets: 30

72. Elon Musk # tweets October 31 - November 7, 2025?
   Slug: elon-musk-of-tweets-october-31-november-7
   Condition ID: None
   End Date: 2025-11-07T17:00:00Z
   Markets: 26

73. Elon Musk # tweets November 7 - November 14, 2025?
   Slug: elon-musk-of-tweets-november-7-november-14
   Condition ID: None
   End Date: 2025-11-14T17:00:00Z
   Markets: 26

74. Elon Musk # tweets November 14 - November 21, 2025?
   Slug: elon-musk-of-tweets-november-14-november-21
   Condition ID: None
   End Date: 2025-11-21T17:00:00Z
   Markets: 26

75. Elon Musk # tweets November 21 - November 28, 2025?
   Slug: elon-musk-of-tweets-november-21-november-28
   Condition ID: None
   End Date: 2025-11-28T17:00:00Z
   Markets: 26

76. Elon Musk # tweets November 28 - December 5, 2025?
   Slug: elon-musk-of-tweets-november-28-december-5
   Condition ID: None
   End Date: 2025-12-05T17:00:00Z
   Markets: 26

77. Elon Musk # tweets December 5 - December 12, 2025?
   Slug: elon-musk-of-tweets-december-5-december-12
   Condition ID: None
   End Date: 2025-12-12T17:00:00Z
   Markets: 26

78. Elon Musk # tweets December 12 - December 19, 2025?
   Slug: elon-musk-of-tweets-december-12-december-19
   Condition ID: None
   End Date: 2025-12-19T17:00:00Z
   Markets: 30

79. Elon Musk # tweets December 19 - December 26, 2025?
   Slug: elon-musk-of-tweets-december-19-december-26
   Condition ID: None
   End Date: 2025-12-26T17:00:00Z
   Markets: 30

80. Elon Musk # tweets December 26 - January 2, 2026?
   Slug: elon-musk-of-tweets-december-26-january-2
   Condition ID: None
   End Date: 2026-01-02T17:00:00Z
   Markets: 30

81. Elon Musk # tweets January 2 - January 9, 2026?
   Slug: elon-musk-of-tweets-january-2-january-9
   Condition ID: None
   End Date: 2026-01-09T17:00:00Z
   Markets: 30

82. Elon Musk # tweets January 9 - January 16, 2026?
   Slug: elon-musk-of-tweets-january-9-january-16
   Condition ID: None
   End Date: 2026-01-16T17:00:00Z
   Markets: 30

83. Elon Musk # tweets January 16 - January 23, 2026?
   Slug: elon-musk-of-tweets-january-16-january-23
   Condition ID: None
   End Date: 2026-01-23T17:00:00Z
   Markets: 38

84. Elon Musk # tweets January 23 - January 30, 2026?
   Slug: elon-musk-of-tweets-january-23-january-30
   Condition ID: None
   End Date: 2026-01-30T17:00:00Z
   Markets: 38

85. Elon Musk # tweets January 30 - February 6, 2026?
   Slug: elon-musk-of-tweets-january-30-february-6
   Condition ID: None
   End Date: 2026-02-06T17:00:00Z
   Markets: 38

86. Elon Musk # tweets February 6 - February 13, 2026?
   Slug: elon-musk-of-tweets-february-6-february-13
   Condition ID: None
   End Date: 2026-02-13T17:00:00Z
   Markets: 30

87. Elon Musk # tweets February 13 - February 20, 2026?
   Slug: elon-musk-of-tweets-february-13-february-20
   Condition ID: None
   End Date: 2026-02-20T17:00:00Z
   Markets: 30

88. Elon Musk # tweets February 20 - February 27, 2026?
   Slug: elon-musk-of-tweets-february-20-february-27
   Condition ID: None
   End Date: 2026-02-27T17:00:00Z
   Markets: 30


Markets DataFrame:

,slug,condition_id,title,end_date,num_markets
0,of-elon-musk-tweets-between-may-31-and-june-7,None,Elon Musk # of tweets May 31 - June 7?,2024-06-07T12:00:00Z,8
1,of-elon-musk-tweets-june-7-14,None,Elon Musk # of tweets June 7-14?,2024-06-14T12:00:00Z,8
2,elon-musk-of-tweets-june-14-21,None,Elon Musk # of tweets June 14-21?,2024-06-21T12:00:00Z,8
3,elon-musk-of-tweets-june-21-28,None,Elon Musk # of tweets June 21-28?,2024-06-28T12:00:00Z,8
4,elon-musk-of-tweets-june-28-july-5,None,Elon Musk # of tweets June 28 - July 5?,2024-07-05T12:00:00Z,8
...,...,...,...,...,...
83,elon-musk-of-tweets-january-23-january-30,None,"Elon Musk # tweets January 23 - January 30, 2026?",2026-01-30T17:00:00Z,38
84,elon-musk-of-tweets-january-30-february-6,None,"Elon Musk # tweets January 30 - February 6, 2026?",2026-02-06T17:00:00Z,38
85,elon-musk-of-tweets-february-6-february-13,None,"Elon Musk # tweets February 6 - February 13, 2...",2026-02-13T17:00:00Z,30
86,elon-musk-of-tweets-february-13-february-20,None,"Elon Musk # tweets February 13 - February 20, ...",2026-02-20T17:00:00Z,30
87,elon-musk-of-tweets-february-20-february-27,None,"Elon Musk # tweets February 20 - February 27, ...",2026-02-27T17:00:00Z,30

In [7]:
# Save musk_blobs to a JSON file for later use
import json

output_file = INTERIM_DATA_DIR / 'musk_polymarket_blobs.json'

with open(output_file, 'w') as f:
    json.dump(musk_blobs, f, indent=2)

print(f"Saved {len(musk_blobs)} market blobs to {output_file}")

# Also save the DataFrame as parquet
df_output = INTERIM_DATA_DIR / 'musk_polymarket_markets.parquet'
musk_markets_df.to_parquet(df_output, index=False)
print(f"Saved markets DataFrame to {df_output}")

Saved 88 market blobs to /Users/vince/Developer/indian_pizza_machine/backend/data/interim/musk_polymarket_blobs.json
Saved markets DataFrame to /Users/vince/Developer/indian_pizza_machine/backend/data/interim/musk_polymarket_markets.parquet

In [8]:
import json

with open(output_file, 'r') as f:
    loaded_blobs = json.load(f)

print(f"Loaded {len(loaded_blobs)} blobs from {output_file}")

Loaded 88 blobs from /Users/vince/Developer/indian_pizza_machine/backend/data/interim/musk_polymarket_blobs.json

In [9]:
# Fetch and add the missing market
missing_slug = "elon-musk-of-tweets-april-4-11-lower-brackets"

print(f"Fetching missing market: {missing_slug}")
missing_market = get_polymarket_condition_id(missing_slug)

if missing_market:
    # Load current JSON
    with open(output_file, 'r') as f:
        current_blobs = json.load(f)
    
    # Check if already exists
    existing_slugs = [blob['slug'] for blob in current_blobs]
    
    if missing_slug not in existing_slugs:
        # Add the missing market
        current_blobs.append(missing_market)
        
        # Save updated JSON
        with open(output_file, 'w') as f:
            json.dump(current_blobs, f, indent=2)
        
        print(f"✓ Added missing market!")
        print(f"  Title: {missing_market['title']}")
        print(f"  Condition ID: {missing_market['condition_id']}")
        print(f"  Total markets now: {len(current_blobs)}")
        
        # Update the DataFrame too
        musk_blobs = current_blobs
        musk_markets_df = pd.DataFrame([
            {
                'slug': blob['slug'],
                'condition_id': blob['condition_id'],
                'title': blob['title'],
                'end_date': blob['end_date'],
                'num_markets': len(blob.get('markets', []))
            }
            for blob in musk_blobs
        ])
        df_output = INTERIM_DATA_DIR / 'musk_polymarket_markets.parquet'
        musk_markets_df.to_parquet(df_output, index=False)
        print(f"✓ Updated parquet file")
    else:
        print(f"Market already exists in JSON")
else:
    print(f"✗ Failed to fetch market")

Fetching missing market: elon-musk-of-tweets-april-4-11-lower-brackets
✓ Added missing market!
  Title: Elon Musk # of tweets April 4-11? (Lower Brackets)
  Condition ID: None
  Total markets now: 89
✓ Updated parquet file